### PR TITLE
fix: rename_by_rule

### PR DESCRIPTION
**Pull request by nanpuyue**

### CODE REVIEW

**Comment by nanpuyue** [comment]
https://github.com/teloxide/teloxide-macros/commit/7c84eead775dc0150d83f75521899e5a2d12b8f3#diff-dee4143cfb8e0db9ec26038710aadb2bc3faad75143fcad328ac46d6fe47ced5L4

**Comment by nanpuyue** [comment]
Fix: https://github.com/teloxide/teloxide/issues/584

**Comment by Hirrolot** [comment]
A relevant excerpt from the documentation of `BotCommand`:

> `#[command(rename = "rule")]` Rename one command by a rule. Allowed rules are `lowercase`, `%some_name%`, where `%some_name%` is any string, a new name.

**Review by Hirrolot — APPROVED** [review]

**Comment by Hirrolot** [comment]
Also fixes https://github.com/teloxide/teloxide/issues/633.

**Pull request merged**
